version: 2.1
jobs:
  base-job:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - aws-cli/setup
      - run: bundle install --gemfile scripts/Gemfile
      - run: ruby scripts/create_sitemap.rb 3000 base sample-sitemap-for-fess
  daily-job:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - aws-cli/setup
      - run: bundle install --gemfile scripts/Gemfile
      - run: ruby scripts/create_sitemap.rb 300 new sample-sitemap-for-fess
orbs:
  aws-cli: circleci/aws-cli@2.0.0
workflows:
  version: 2
  daily:
    triggers:
      - schedule:
          cron: "0 0 * * 0" # JST - 9時間 を指定する
          filters:
            branches:
              only:
                - test # TODO cron停止するため存在しないブランチを指定している
    jobs:
      - daily-job
  base:
    triggers:
      - schedule:
          cron: "30 0 * * *" # JST - 9時間 を指定する
          filters:
            branches:
              only:
                - test # TODO cron停止するため存在しないブランチを指定している
    jobs:
      - base-job